<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="7858" started-at="2020-03-17T10:00:11Z" finished-at="2020-03-17T10:00:19Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="7858" started-at="2020-03-17T10:00:11Z" finished-at="2020-03-17T10:00:19Z">
      <class name="HelloMaven.testcase.testLogin">
        <test-method status="PASS" signature="getLoginHome()[pri:0, instance:HelloMaven.testcase.testLogin@8f2ef19]" name="getLoginHome" duration-ms="7824" started-at="2020-03-17T18:00:11Z" finished-at="2020-03-17T18:00:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLoginHome -->
        <test-method status="FAIL" signature="Login()[pri:0, instance:HelloMaven.testcase.testLogin@8f2ef19]" name="Login" duration-ms="2" started-at="2020-03-17T18:00:19Z" depends-on-methods="HelloMaven.testcase.testLogin.getLoginHome" finished-at="2020-03-17T18:00:19Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at HelloMaven.base.ElementProperties.bystr(ElementProperties.java:12)
	at HelloMaven.page.LoginPage.getUserName(LoginPage.java:22)
	at HelloMaven.Handle.LoginHandle.IsLoginPage(LoginHandle.java:31)
	at HelloMaven.business.LoginPro.Login(LoginPro.java:13)
	at HelloMaven.testcase.testLogin.Login(testLogin.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method status="SKIP" signature="stop()[pri:0, instance:HelloMaven.testcase.testLogin@8f2ef19]" name="stop" duration-ms="0" started-at="2020-03-17T18:00:19Z" depends-on-methods="HelloMaven.testcase.testLogin.Login" finished-at="2020-03-17T18:00:19Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method testLogin.stop()[pri:0, instance:HelloMaven.testcase.testLogin@8f2ef19] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method testLogin.stop()[pri:0, instance:HelloMaven.testcase.testLogin@8f2ef19] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stop -->
      </class> <!-- HelloMaven.testcase.testLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
